security:
    factories:
        - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"
        - "%kernel.root_dir%/../vendor/bundles/FOS/GoogleBundle/Resources/config/security_factories.xml"
    providers:
        chain_provider:
            providers: [fos_userbundle, fos_facebook_provider] 
            #, fos_google_provider
        fos_userbundle:
            id: fos_user.user_manager 
        fos_facebook_provider:
            id: ks_facebook
        ks_user_provider:
            id: ks_user.provider
        #fos_google_provider:
            #id: ks_google
 
    firewalls:
        main:
            pattern: ^/
            fos_facebook:
                app_url: "http://apps.facebook.com/psiware/"
                #server_url: /activities/newsFeed
                server_url: %host%
                login_path: /login
                check_path: /login_check_facebook
                default_target_path: /activities/newsFeed
                provider: fos_facebook_provider
            #fos_google:
                #provider: fos_google_provider
                #check_path: /google/login
            form_login:
                provider:     ks_user_provider
                remember_me: true
                success_handler: ks.success_handler
                #success_handler: ks_user.success_authentication_handler
                login_path:   /login
                check_path:   /login_check
                use_forward:  false
                failure_path: null
                default_target_path: /activities/newsFeed
                use_referer:        true
                always_use_default_target_path: false
            logout:
                path:   /logout
                target: /login
                handlers: ["fos_facebook.logout_handler"] 
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000
                path:     /
                domain:   ~    
                #always_remember_me: true
                #remember_me_parameter: _remember_me
              
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512


    # C'est ici que tout se passe : qui a accès à quoi ?
    access_control:
        - { path: ^/$,                                  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$,                             role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check_facebook$,              role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,                           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,                          role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # validation paybox
        - { path: ^/payment/validate,                   role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        #fichiers
        - { path: ^/ico/favicon.ico,                    role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        #activités
        - { path: ^/activities/newsFeed$,               role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/activities/load/.*$,                role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/activities/*,                       role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/activities/sendDayActivitiesMails,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/activities/getDataGraph/*,          role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/activities/V2,                      role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        #activités sportives
        - { path: ^/sportingActivities/localisations$,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sportingActivities/search$,         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sportingActivities/loadGoogleMapBubbleContent/.*$,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        #users
        - { path: ^/change_language/,                    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sportifs$,                           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/searchUsers$,                        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/consultBlog$,                        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/postFeedback$,                       role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        #dachboard
        - { path: ^/dashboard/getDataGraphTopLeaguesUsers/,   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard/getDataGraphDependingOnSport/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/agenda/*,                            role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard/getDataComparisonTool/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        #coaching
        - { path: ^/coaching/getCoachingGraph/*,        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/coaching/*,                         role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        #wikisport
        - { path: ^/wikisport/index$,                   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/wikisport/category/.*/list$,        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/wikisport/.*/show$,                 role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/wikisport/competitions$,            role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        #shops
        - { path: ^/shops/.$,                           role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        #leagues
        - { path: ^/leagues/ranking$,                   role: IS_AUTHENTICATED_ANONYMOUSLY } 
        
        #contest
        - { path: ^/contests/coach$,                    role: IS_AUTHENTICATED_ANONYMOUSLY } 
        
        #autres
        - { path: ^/search/$,                           role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/legal_mentions$,                    role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/general_conditions$,                role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sales_conditions$,                  role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        #barre de dev
        - { path: ^/_wdt/*,                             role: IS_AUTHENTICATED_ANONYMOUSLY }

        
        - { path: ^/admin/,                             role: ROLE_ADMIN }
        - { path: ^/facebook/,                          role: [ROLE_FACEBOOK] }
        - { path: ^/google/,                            role: [ROLE_GOOGLE] }

        - { path: ^/fos_js_routing,                     role: IS_AUTHENTICATED_ANONYMOUSLY }
         
        - { path: ^/.*,                                 role: ROLE_USER }
        
        #pour les tests
        #- { path: ^/.*,                                 role: IS_AUTHENTICATED_ANONYMOUSLY }
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

