<?php

namespace Ks\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NetaffiliationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NetaffiliationRepository extends EntityRepository
{
    public function findReferencesOrberBySports( ) {
        $dbh        = $this->_em->getConnection();
        
        $vars       = array();  
        $sqlParts   = array(
            'select' => 'SELECT'
                .' netaffiliation.reference, sport.codeSport'
            ,
            'from'  => 'FROM ks_netaffiliation netaffiliation'
            .' INNER JOIN ks_netaffiliation_for_sport netaffiliation_sport on (netaffiliation.id = netaffiliation_sport.netaffiliation_id)'
            .' INNER JOIN ks_sport sport on (netaffiliation_sport.sport_id = sport.id)'
            ,
            'where' => "WHERE 1",
            'group' => 'GROUP BY netaffiliation.id',
            'order' => '',
            'limit' => ''
        );    
        
        $stmt = $dbh->executeQuery(implode(' ', $sqlParts), $vars);
        
        $netaffiliations = array();
        while( $netaffiliation = $stmt->fetch(\PDO::FETCH_ASSOC) ) {
                
            $netaffiliations[$netaffiliation["codeSport"]][] = $netaffiliation["reference"];
        }
        
        return $netaffiliations;
    }
}