<?php

namespace Ks\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
    
    public function activateService( $serviceId, $userId ) {
        $em = $this->_em;
        $userHasServicesRep      = $em->getRepository('KsUserBundle:UserHasServices');
    
        $userHasService = $userHasServicesRep->findOneBy( array(
            "user" => $userId,
            "service" => $serviceId
        ));
        
        if( is_object( $userHasService )) {
            $userHasService->setIsActive( true );
            $em->persist( $userHasService );
            $em->flush();
        }
    }
    
    public function deactivateService( $serviceId, $userId ) {
        $em = $this->_em;
        $userHasServicesRep      = $em->getRepository('KsUserBundle:UserHasServices');
    
        $userHasService = $userHasServicesRep->findOneBy( array(
            "user" => $userId,
            "service" => $serviceId
        ));
        
        if( is_object( $userHasService )) {
            $userHasService->setIsActive( false );
            $em->persist( $userHasService );
            $em->flush();
        }
    }
}
