<?php

namespace Ks\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipmentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasSportPackageFromClubRepository extends EntityRepository
{
    /**
     * Pour supprimer le forfait d'un user pour un club donné
     */
    public function deleteUserHasSportPackageFromClub($clubId, $userId)
    {
        $dbh    = $this->_em->getConnection();
        $stmt   = $dbh->executeQuery(
            'delete from ks_user_has_sport_package_from_club where club_id = ? and user_id = ?',
            array($clubId, $userId)
        );
        $this->_em->flush();
    }
    
}