<?php

namespace Ks\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserHasFriendsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasToDoChecklistActionRepository extends EntityRepository
{
    /**
     * Est-ce que user friend sont amis ?
     *
     * @param type $userId
     * @param type $friendId
     * @return boolean 
     */
    public function findActionsToDo($userId)
    {
        $sql =
            'SELECT ca.id, ca.label, ca.code, uuhca.date'
            .' FROM ks_checklist_action ca'
            .' INNER JOIN ks_user_has_checklist_action uuhca ON (uuhca.checklistAction_id = ca.id)'
            .' WHERE user_id = :userId'
            //.' AND uuhca.date IS NULL'
            .' ORDER BY uuhca.date, ca.rank';

        $dbh = $this->_em->getConnection();
        
        $stmt = $dbh->prepare($sql);
        $stmt->execute(array('userId' => $userId));
        
        return $stmt->fetchAll(\PDO::FETCH_ASSOC);
    }
    
    public function findByUserAndChecklistAction($userId, $checklistActionId)
    {
        $sql =
            'SELECT date '
            .' FROM ks_user_has_checklist_action'
            .' WHERE user_id = :userId'
            .' AND checklistAction_id = :checklistActionId';

        $dbh = $this->_em->getConnection();
        
        $stmt = $dbh->prepare($sql);
        $stmt->execute(array('userId' => $userId, 'checklistActionId' => $checklistActionId));
        
        return $stmt->fetchAll(\PDO::FETCH_ASSOC);
    }
}