<?php

namespace Ks\ActivityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     *
     * @return array collection de commentaires des amis qui ne sont pas encore affichées sur la page de l'utilisateur
     */
    public function findNotDisplayedFriendComments(\Ks\UserBundle\Entity\User $user, $lastRefreshTime)
    {      
        $queryBuilder = $this->_em->createQueryBuilder();
 
        $queryBuilder->select('c')
                ->from('KsActivityBundle:Comment', 'c')
                ->innerJoin('c.user', 'u')
                ->leftJoin('u.friendsWithMe', 'f1')
                ->leftJoin('u.myFriends', 'f2')
                ->where('f1.user = ?1')
                ->orWhere('f2.friend = ?1')
                ->orWhere('u.id = ?1')
                ->andWhere('c.commentedAt > ?2')
                //->andWhere('a.id > ?3')
                ->orderBy('c.commentedAt', 'ASC')
                ->setParameter(1, $user->getId())
                ->setParameter(2, date('Y-m-d H:i:s', $lastRefreshTime));
                //->setParameter(3, $lastDisplayedActivityId);

        $query = $queryBuilder->getQuery();
        
        return $query->getResult();
    }
}