<?php

namespace Ks\ActivityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserModifiesArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserModifiesArticleRepository extends EntityRepository
{
     /**
     *
     * @param string $articleLabel
     * @return boolean exist or not
     */
    public function getLastModification(\Ks\ActivityBundle\Entity\Article $article)
    {   
        $qb = $this->_em->createQueryBuilder();

        $qb ->select('uwmsc')
            ->from('KsActivityBundle:UserModifiesArticle', 'uwmsc')
            ->where("uwmsc.article = ?1")
            ->orderBy("uwmsc.modifiedAt", "desc")
            ->setMaxResults(1)
            ->setParameter(1, $article->getId());
        
        $query = $qb->getQuery();
        //$result = $query->getSingleResult() ? $query->getSingleResult() : array();
        $result = $query->getOneOrNullResult() != null ? $query->getOneOrNullResult() : array();
        
        return $result;
    }
    
    public function findFiveLastModifiedArticles()
    {   
        $qb = $this->_em->createQueryBuilder();

        $qb ->select('uwmsc')
            ->from('KsActivityBundle:UserModifiesArticle', 'uwmsc')
            ->orderBy("uwmsc.modifiedAt", "desc")
            ->groupBy("uwmsc.article")
            ->setMaxResults(5);
        
        $query = $qb->getQuery();
        
        return $query->getResult();
    }
}