<?php

namespace Ks\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationTypeRepository extends EntityRepository
{
    public function findNotificationTypeIdByNotificationTypeName( $notificationTypeName ) {
        $dbh = $this->_em->getConnection();
        
        $sql =   "SELECT nt.id "
                ." FROM ks_notification_type nt  "
                ." WHERE nt.name = :notificationTypeName ";
        
        $stmt = $dbh->executeQuery($sql, array(
            'notificationTypeName'  => $notificationTypeName,
        ));
        
        return $stmt->fetch(\PDO::FETCH_COLUMN);
    }
}