<?php

namespace Ks\NotificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserReceivesMailNotificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserReceivesMailNotificationsRepository extends EntityRepository
{
}