parameters:
#    bold_image.example.class: Bold\ImageBundle\Example

services:
#    bold_image.example:
#        class: %bold_image.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
