<?php

namespace Ks\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShopHasVotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopHasVotesRepository extends EntityRepository
{
}