<?php

namespace Ks\LeagueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LeagueLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueLevelRepository extends EntityRepository
{
    public function updateUserLeagueLevel(\Ks\LeagueBundle\Entity\LeagueLevel $leagueLevel, \Ks\UserBundle\Entity\User $user )
    {
        if( $user->getLeagueLevel()->getId() != $leagueLevel->getId() ) {
            
            if ( $user->getLeagueLevel()->getId() > $leagueLevel->getId() ) {
                $updateState = "up";
            } else {
                $updateState = "down";
            }
            $user->setLeagueLevel($leagueLevel);
            $this->_em->persist($user);
            $this->_em->flush();

            
            if ( $user->getLeagueLevel()->getId() == $leagueLevel->getId() ) {
                return $updateState;
            } else {
                return "stable";
            }
        } else {
            return "stable";
        }
    }
    
    public function getLowestRank()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb ->select('MAX(ll.rank)')
            ->from('KsLeagueBundle:LeagueLevel', 'll');

        return $qb->getQuery()->getSingleScalarResult();
    }
    
    public function getLeagueLevelSup($rank)
    {
        $rankSup = $rank - 1;

        $qb = $this->_em->createQueryBuilder();
        $qb ->select('ll')
            ->from('KsLeagueBundle:LeagueLevel', 'll')
            ->where('ll.rank = ?1')
            ->setParameter(1, $rankSup);

        return $qb->getQuery()->getSingleResult();
    }
    
    public function getLeagueLevelInf($rank)
    {
        $rankInf = $rank + 1;

        $qb = $this->_em->createQueryBuilder();
        $qb ->select('ll')
            ->from('KsLeagueBundle:LeagueLevel', 'll')
            ->where('ll.rank = ?1')
            ->setParameter(1, $rankInf);

        return $qb->getQuery()->getSingleResult();
    }
    
    public function getInfRankWith0star($rank)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb ->select('MIN(ll.rank)')
            ->from('KsLeagueBundle:LeagueLevel', 'll')
            ->where('ll.rank > ?1')
            ->andWhere('ll.starNumber = ?2')
            ->setParameter(1, $rank)
            ->setParameter(2, 0);

        return $qb->getQuery()->getSingleScalarResult();
    }
    
    public function findUsersByCategory(\Ks\LeagueBundle\Entity\LeagueCategory $leagueCategory)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb ->select('u')
            ->from('KsUserBundle:User', 'u')
            ->innerJoin('u.leagueLevel', 'll')
            ->where('ll.category = ?1')
            ->setParameter(1, $leagueCategory->getId());
        
        return $qb->getQuery()->getResult();
    }
    
    public function findUsersOfMyCommunityByCategory($leagueCategory, $myCommunityIds, \DateTime $beginDate)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb ->select('u')
            ->addSelect('SUM(p.points) as totalPoints')
            ->from('KsUserBundle:User', 'u')
            ->innerJoin('u.leagueLevel', 'll')
            ->innerJoin('u.myPoints', 'p')
            ->innerJoin('p.activitySession', 'a')
            ->where('u.id in (?2)')
            ->andWhere('ll.category = ?1')
            ->andWhere('a.issuedAt > ?3')
            ->andWhere('a.isDisabled != TRUE')
            ->andWhere('a.isValidate != FALSE')
            ->addOrderBy('ll.starNumber', 'DESC')
            ->addOrderBy('totalPoints', 'DESC')
            ->groupBy('u')            
            ->setParameter(1, $leagueCategory->getId())
            ->setParameter(2, $myCommunityIds)
            ->setParameter(3, $beginDate);
        
        $usersWhoHaveAlreadyEarnedPoints = $qb->getQuery()->getResult();
        
        $usersIdWhoHaveAlreadyEarnedPoints = array();
        foreach( $usersWhoHaveAlreadyEarnedPoints as $result ) {
            if( isset( $result[0] ) ) {
                $usersIdWhoHaveAlreadyEarnedPoints[] = $result[0]->getId();
            } 
            //var_dump($result[0]->getId());
        }

        //$usersIdToGet = array_diff($myCommunityIds, $usersIdWhoHaveAlreadyEarnedPoints);
        
        $usersIdToGet = array();
        foreach( $myCommunityIds as $userId ) {
            if( !in_array( $userId, $usersIdWhoHaveAlreadyEarnedPoints )) {
                $usersIdToGet[] = $userId;
            }
        }
        //var_dump($usersIdToGet);*/
        
        if( !empty( $usersIdToGet )) {
            $qb = $this->_em->createQueryBuilder();
            $qb ->select('u')
                ->addSelect('0 as totalPoints')
                ->from('KsUserBundle:User', 'u')
                ->innerJoin('u.leagueLevel', 'll')
                ->where('u.id in (?2)')
                ->andWhere('ll.category = ?1')  
                ->addOrderBy('ll.starNumber', 'DESC')
                ->groupBy('u')            
                ->setParameter(1, $leagueCategory->getId())
                ->setParameter(2, $usersIdToGet);

            $usersWhoHaveNeverEarnedPoints = $qb->getQuery()->getResult();

            $users = array_merge($usersWhoHaveAlreadyEarnedPoints, $usersWhoHaveNeverEarnedPoints);
        } else {
            $users = $usersWhoHaveAlreadyEarnedPoints;
        }
        
        
            
            /*$orModule = $qb->expr()->orx();
            $orModule->add($qb->expr()->eq('a.isDisabled', FALSE));
            $orModule->add($qb->expr()->eq('a.isDisabled', NULL));
            $qb->andWhere($orModule);
            
            
            $orModule2 = $qb->expr()->orx();
            $orModule2->add($qb->expr()->eq('a.isValidate', TRUE));
            $orModule2->add($qb->expr()->eq('a.isValidate', NULL));
            $qb->andWhere($orModule2);*/

//var_dump($qb->getQuery()->)
        return $users;
    }
    
    public function findNbUsersOfMyCommunityByLeagueLevels($myCommunityIds)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb ->select('ll.id', 'COUNT(u.id) as nb')
            //->from('KsLeagueBundle:LeagueLevel', 'll')
            ->from('KsUserBundle:User', 'u')
            ->where('u.id in (?1)') 
            ->innerJoin('u.leagueLevel', 'll')
            //->leftJoin('u. u ON u.leagueLevel_id = ll.id', 'll')
            //->leftJoin('u.leagueLevel', 'll')

            //->addFrom('KsUserBundle:User', 'u')
            //->leftJoin('u.friendsWithMe', 'f1')
            //->leftJoin('u.myFriends', 'f2');
        
        /*$orModule = $qb->expr()->orx();
        $orModule->add($qb->expr()->eq('f1.user', '?1'));
        $orModule->add($qb->expr()->eq('f2.friend', '?1'));
        $orModule->add($qb->expr()->eq('u.id', '?1'));*/
        
        //$qb ->andWhere($orModule)
            ->setParameter(1, $myCommunityIds)
            ->groupBy('ll.id');
        
        /*SELECT ll.id, ll.label, COUNT(u.id) as nb
FROM ks_league_level ll
LEFT JOIN ks_user u ON u.leagueLevel_id = ll.id
GROUP BY ll.id
*/

        return $qb->getQuery()->getResult();
        
        /*$sql = "SELECT ll.id, COUNT(u.id) as nb
                FROM ks_league_level ll 
                LEFT JOIN ks_user u ON u.leagueLevel_id = ll.id
                GROUP BY ll.id"; 

        $rsm = new \Doctrine\ORM\Query\ResultSetMapping;
        $rsm->addEntityResult($this->getEntityName(), "LeagueLevel");
        $rsm->addFieldResult("LeagueLevel", "id", "id");
        $rsm->addJoinedEntityResult('Ks\UserBundle\Entity\User' , 'User', 'u', 'u.leagueLevel');
        //$rsm->addEntityResult('Ks\UserBundle\Entity\User', "User");
        $rsm->addFieldResult('User', 'nb', 'nb');
        $rsm->getEntityResultCount();
        $query = $this->_em->createNativeQuery($sql , $rsm);
        
        /*$query = $this->_em->createQuery(
            "  SELECT ll.id, COUNT(u.id) as nb"
            ." FROM KsLeagueBundle:LeagueLevel ll "
            ." LEFT JOIN ks_user u ON u.leagueLevel_id = ll.id"
            ." GROUP BY ll.id"
        );*/
        /*$query = $this->_em->createQuery(
            "  SELECT ll.id, COUNT(u.id) as nb"
            ." FROM KsLeagueBundle:LeagueLevel ll "
            ." LEFT JOIN KsUserBundle:User u ON u.leagueLevel = ll.id"
            ." GROUP BY ll.id"
        );*/
        //$query->setParameters(array($user->getId(), $friend));
        
        //return $query->getSingleScalarResult();
        
        //var_dump($query->getSQL());*/
        //return $query->getArrayResult();
    }
    
    public function findNbUsersByCategory(\Ks\LeagueBundle\Entity\LeagueCategory $leagueCategory)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb ->select('COUNT(u)')
            ->from('KsUserBundle:User', 'u')
            ->innerJoin('u.leagueLevel', 'll')
            ->where('ll.category = ?1')
            ->setParameter(1, $leagueCategory->getId());

        $query = $qb->getQuery();
        return (int) $query->getSingleScalarResult();
    }
    
     public function updateLeagueLevel( $userId, $leagueLevelId ) {
        $dbh = $this->_em->getConnection();
        
        $sql =   "UPDATE ks_user u "
                ." SET `leagueLevel_id` = :leagueLevelId "
                ." WHERE u.id = :userId";
        
        $dbh->executeQuery($sql, array(
            'userId'            => $userId,
            'leagueLevelId'     => $leagueLevelId,
        ));
    }
    
    public function findLeagueLevelIdByCategoryIdAndStars( $leagueCategoryId, $starsNumber ) {
        $dbh = $this->_em->getConnection();
        
        $sql =   "SELECT ll.id "
                ." FROM ks_league_level ll  "
                ." WHERE ll.category_id = :leagueCategoryId "
                ." AND ll.starNumber = :starsNumber ";
        
        $stmt = $dbh->executeQuery($sql, array(
            'leagueCategoryId'  => $leagueCategoryId,
            'starsNumber'       => $starsNumber,
        ));
        
        return $stmt->fetch(\PDO::FETCH_COLUMN);
    }
    
    public function findLeagueLevelIdByLeagueLevelLabel( $leagueLevelLabel ) {
        $dbh = $this->_em->getConnection();
        
        $sql =   "SELECT ll.id "
                ." FROM ks_league_level ll  "
                ." WHERE ll.label = :leagueLevelLabel ";
        
        $stmt = $dbh->executeQuery($sql, array(
            'leagueLevelLabel'  => $leagueLevelLabel,
        ));
        
        return $stmt->fetch(\PDO::FETCH_COLUMN);
    }
    
    public function findLeagueLevelIdByCategoryLabelAndStars( $leagueCategoryLabel, $starsNumber ) {
        $dbh = $this->_em->getConnection();
        
        $sql =   "SELECT ll.id "
                ." FROM ks_league_level ll "
                ." INNER JOIN ks_league_category lc ON ll.category_id = lc.id "
                ." WHERE lc.label = :leagueCategoryLabel "
                ." AND ll.starNumber = :starsNumber ";
        
        $stmt = $dbh->executeQuery($sql, array(
            'leagueCategoryLabel'  => $leagueCategoryLabel,
            'starsNumber'       => $starsNumber,
        ));
        
        return $stmt->fetch(\PDO::FETCH_COLUMN);
    }
    
    public function findStarsNumberByLeagueLevelId( $leagueLevelId ) {
        $dbh = $this->_em->getConnection();
        
        $sql =   "SELECT ll.starNumber "
                ." FROM ks_league_level ll "
                ." WHERE ll.id = :leagueLevelId ";
        
        $stmt = $dbh->executeQuery($sql, array(
            'leagueLevelId'     => $leagueLevelId,
        ));
        
        return $stmt->fetch(\PDO::FETCH_COLUMN);
    }
    
    public function findLeagues( $params = array(), $translator = null ) {
        $dbh            = $this->_em->getConnection();
        
        $vars       = array();  
        $sqlParts   = array(
            'select' => 'SELECT'
                .' ll.id, ll.rank, ll.label, ll.starNumber,'
                .' ll_category.id as categoryId, ll_category.label as categoryCode'
            ,
            'from'  => 'FROM ks_league_level ll'
                .' LEFT JOIN ks_league_category ll_category on (ll.category_id = ll_category.id)'
                ,
            'where' => "WHERE 1",
            'group' => '',
            'order' => '',
            'limit' => ''
        );
        
        $stmt = $dbh->executeQuery(implode(' ', $sqlParts), $vars);
        
        $leagues = array();
        while( $league = $stmt->fetch(\PDO::FETCH_ASSOC) ) {
            if ( $translator != null ) {
                $league["label"] = $translator->trans( "leagues." . $league["categoryCode"] ) . " " . $league["starNumber"];
                $league["categoryLabel"] = $translator->trans( "leagues." . $league["categoryCode"] );
            } 
            
            $leagues[] = $league;
        }
        
        return $leagues;
    }
}