<?php

namespace Ks\AgendaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AgendaHasEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaHasEventsRepository extends EntityRepository
{
    
    public function eventIsInAgenda(\Ks\AgendaBundle\Entity\Agenda $agenda, \Ks\EventBundle\Entity\Event $event)
    {
        $queryBuilder = $this->_em->createQueryBuilder();
        $queryBuilder->select('count(e.id)')
                ->from('KsAgendaBundle:AgendaHasEvents', 'ahe')
                ->innerJoin('ahe.agenda', 'a')
                ->innerJoin('ahe.event', 'e')
                ->where('a.id = ?1')
                ->andWhere('e.id = ?2')
                ->setParameter(1, $agenda->getId())
                ->setParameter(2, $event->getId());
        
        $query = $queryBuilder->getQuery();
        
        $result = (int)$query->getSingleScalarResult();

        return ($result == 1 ? true : false);
    }
    
    public function addEventToAgenda(\Ks\AgendaBundle\Entity\Agenda $agenda, \Ks\EventBundle\Entity\Event $event)
    {
        $agendaHasEvents = new \Ks\AgendaBundle\Entity\AgendaHasEvents($agenda, $event);

        $this->_em->persist($agendaHasEvents);
        $this->_em->flush();
    }
    
    public function removeEventToAgenda(\Ks\AgendaBundle\Entity\AgendaHasEvents $agendaHasEvents)
    {
        $this->_em->remove($agendaHasEvents);
        $this->_em->flush();
    }

}