<?php

namespace Ks\TrophyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShowcaseExposesTrophiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowcaseExposesTrophiesRepository extends EntityRepository
{
    public function exposeTrophieInShowcase(\Ks\TrophyBundle\Entity\Showcase $showcase, \Ks\TrophyBundle\Entity\Trophy $trophy) {
        $showcaseExposesTrophies = new ShowcaseExposesTrophies($showcase, $trophy);       
        $this->_em->persist($showcaseExposesTrophies);
        $this->_em->flush();
    }
    
    public function takeOfTrophyFromShowcase(\Ks\TrophyBundle\Entity\ShowcaseExposesTrophies $showcaseExposesTrophies)
    {      
        $this->_em->remove($showcaseExposesTrophies);
        $this->_em->flush();
    }
    
    public function isAlreadyInShowcase(\Ks\TrophyBundle\Entity\Showcase $showcase, \Ks\TrophyBundle\Entity\Trophy $trophy) {
        $queryBuilder = $this->_em->createQueryBuilder();
        $queryBuilder->select('count(st)')
                ->from('KsTrophyBundle:ShowcaseExposesTrophies', 'st')
                ->where('st.showcase = ?1')
                ->andWhere('st.trophy = ?2')
                ->setParameter(1, $showcase->getId())
                ->setParameter(2, $trophy->getId());
        
        $query = $queryBuilder->getQuery();
        
        $result = (int)$query->getSingleScalarResult();

        return ($result == 0 ? false : true);
    }
    
    public function isFull(\Ks\TrophyBundle\Entity\Showcase $showcase) {
        $queryBuilder = $this->_em->createQueryBuilder();
        $queryBuilder->select('count(st)')
                ->from('KsTrophyBundle:ShowcaseExposesTrophies', 'st')
                ->where('st.showcase = ?1')
                ->setParameter(1, $showcase->getId());
        
        $query = $queryBuilder->getQuery();
        
        $result = (int)$query->getSingleScalarResult();

        return ($result < 5 ? false : true);
    }
    
}