<?php

namespace Ks\TrophyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShowcaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowcaseRepository extends EntityRepository
{
}