<?php

namespace Ks\TrophyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrophyCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrophyCategoryRepository extends EntityRepository
{
    public function findTrophyCategoryIdByCode( $trophyCategoryCode )
    {
        $dbh = $this->_em->getConnection();
        $sql = "SELECT tc.id"
            ." FROM ks_trophy_category tc"
            ." WHERE tc.code = :trophyCategoryCode ";
        
        $stmt = $dbh->executeQuery($sql, array(
            'trophyCategoryCode'  => $trophyCategoryCode
        ));

        return $stmt->fetch(\PDO::FETCH_COLUMN);
    }
}