jQuery(function($){
	$(".btn-check").click(function(){
		$('.btn-check').each(function(){
			$(this).attr('src','./images/check.jpg');
		});
		$(this).attr('src','./images/checkeed.jpg');
		$(this).attr('checked','checked');
		
	});
	$(".btn-check2").click(function(){
		$('.btn-check2').each(function(){
			$(this).attr('src','./images/ch-m.jpg');
		});
		$(this).attr('src','./images/ch-mC.jpg');
		$(this).attr('checked','checked');		
	});

	$("#p1").click(function(){
		$(".voile-2").hide();
		$(".voile-3").hide();
		$('.btn-check2').each(function(){
			$(this).attr('src','./images/ch-m.jpg');
		});
		$("#montreW1").attr('src','./images/ch-mC.jpg');
		$("#montreW2").attr('src','./images/ch-mC.jpg');
		$(".btn-check3").attr('src','./images/ch-mC.jpg');
	});
	$("#p2").click(function(){
		$(".voile-2").hide();
		$(".voile-3").hide();
		$('.btn-check2').each(function(){
			$(this).attr('src','./images/ch-m.jpg');
		});
		$("#montreW3").attr('src','./images/ch-mC.jpg');
		$("#montreW4").attr('src','./images/ch-mC.jpg');
		$(".btn-check3").attr('src','./images/ch-mC.jpg');
	});
	$("#p3").click(function(){
		$(".voile-2").hide();
		$(".voile-3").show();
		$('.btn-check2').each(function(){
			$(this).attr('src','./images/ch-m.jpg');
		});
		$(".btn-check3").attr('src','./images/ch-m.jpg');
		$("#montreW1").attr('src','./images/ch-mC.jpg');
		$("#montreW2").attr('src','./images/ch-mC.jpg');
	});
	$("#p4").click(function(){
		$(".voile-2").hide();
		$(".voile-3").show();
		$('.btn-check2').each(function(){
			$(this).attr('src','./images/ch-m.jpg');
		});
		$(".btn-check3").attr('src','./images/ch-m.jpg');
		$("#montreW3").attr('src','./images/ch-mC.jpg');
		$("#montreW4").attr('src','./images/ch-mC.jpg');
	});
	$("#p5").click(function(){
		$(".voile-2").show();
		$(".voile-3").show();
		$('.btn-check2').each(function(){
			$(this).attr('src','./images/ch-m.jpg');
		});
		$('.btn-check').each(function(){
			$(this).attr('src','./images/check.jpg');
		});
		$(".btn-check3").attr('src','./images/ch-m.jpg');
	});
});