parameters:
#    ks_message.example.class: Ks\MessageBundle\Example

services:
#    ks_message.example:
#        class: %ks_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
