<?php

namespace Ks\ClubBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository
{
    
     /**
     *
     * @return int Nombre total d'activités dans la base pour un utilisateur
     */
    public function getMemberByClub(\Ks\ClubBundle\Entity\Club $club)
    {      
        $queryBuilder = $this->_em->createQueryBuilder();
        $queryBuilder->select('m')
                ->from('KsClubBundle:Member' , 'm' )
                ->innerJoin('m.clubs', 'chm')
                ->where('chm.club = ?1')
                ->orderBy("m.lastname", "ASC")
                ->setParameter(1, $club->getId());
        
        return $queryBuilder;
 
    }
    
    
}