<?php

namespace Ks\ClubBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamCompositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamCompositionRepository extends EntityRepository
{
    /**
     *
     * @return query builder des équipes adverses classés par ordre alphabétique
     */
    public function findTeamCompositionsQB( \Ks\ClubBundle\Entity\Team $team )
    {      
        $queryBuilder = $this->_em->createQueryBuilder();
 
        $queryBuilder->select('tc')
                ->from('KsClubBundle:TeamComposition', 'tc')
                ->leftJoin('tc.team', 't')
                ->andWhere('t.id = ?0')
                ->setParameter(0, $team->getId())
                ->orderBy('tc.date', 'Desc');

        return $queryBuilder;
    }
    
    public function publishTeamComposition(\Ks\ClubBundle\Entity\TeamComposition $teamComposition)
    {
        $notificationTypeRep = $this->_em->getRepository( "KsNotificationBundle:NotificationType" );
        $notificationType_teamComposition = $notificationTypeRep->findOneByName( "teamComposition" );
        
        if( is_object( $notificationType_teamComposition ) ) {
            $abstractActivity = new \Ks\ActivityBundle\Entity\AbstractActivity( $notificationType_teamComposition );
            $abstractActivity->setClub( $teamComposition->getTeam()->getClub() );
            $abstractActivity->setTeamComposition( $teamComposition );

            $teamComposition->addAbstractActivity( $abstractActivity );

            $this->_em->persist( $abstractActivity );
            $this->_em->persist( $teamComposition );
            $this->_em->flush();

            return $abstractActivity;
        } 
        
        return null;
    }
}