<?php

namespace Ks\ClubBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserManageClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserManageClubRepository extends EntityRepository
{
     /**
     *
     * @return boolean
     */
    public function userIsClubManager(\Ks\ClubBundle\Entity\Club $club, \Ks\UserBundle\Entity\User $user )
    {      
        /*$queryBuilder = $this->_em->createQueryBuilder();
 
        $queryBuilder->select('umc')
                ->from('KsClubBundle:UserManageClub', 'umc')
                ->where('umc.club = ?0')
                ->andWhere('umc.user = ?1')
                ->setParameter(0, $club->getId())
                ->setParameter(1, $user->getId());

        $query = $queryBuilder->getQuery();
        
        $result = (int)$query->getSingleScalarResult();

        return ($result == 1 ? true : false);
        return true;*/
        
        $dbh    = $this->_em->getConnection();
        $stmt   = $dbh->executeQuery(
            'select count(user_id)'
            .' FROM  ks_user_manage_clubs'
            .' WHERE club_id = :clubId '
            .' AND user_id = :userId',
            array(
                'userId'    => $user->getId(),
                'clubId'  => $club->getId()
            )
        );
        
        return $stmt->fetchColumn() > 0 ? true : false;
    }
    
    public function addUserAsManager(\Ks\ClubBundle\Entity\Club $club, \Ks\UserBundle\Entity\User $user )
    {      
        $userManageClub = new \Ks\ClubBundle\Entity\UserManageClub( $club, $user );
        $club->addUserManageClub( $userManageClub );
        
        $this->_em->persist($userManageClub);
        $this->_em->persist($club);
        $this->_em->flush();
    }
}