<?php

namespace Ks\EvolutionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvolutionHasVotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvolutionHasVotesRepository extends EntityRepository
{
}